### ISSUE TITLE
Allowing Genomic category

### ISSUE THREAD

**Issue by callumparr** [mortazavilab/TALON#105]
We have prepared our full-length RNAseq samples using a cap-trapping protocol along with oligo-dT priming on polyadenylated total RNA. We hope to try and identify transcript models for actively transcribed RNAs from enhancers. As these may be located within clusters within intronic regions I wanted to permit Genomic novelty and use CAGE evidence to provide further evidence they are genuine transcript isoforms and not say genomic DNA carry-over during RNA extraction. We thought this would be OK because during our library prep we are selecting for capped-molecules of which intronic. 

1. Is there some other rationale by default to remove genomic? Other than it potentially being genomic DNA contamination
2. Do you know how often something is labelled as Genomic novelty from SIRV spike-ins (false positive). 
3. How to identify it is Genomic during the TALON process. 
4. How does TALON handle nascent RNA (unspliced or in process of being spliced?)

**Comment by fairliereese** [comment]
1. This actually ties into question number 4: many genomic reads that I've seen in long-read data are short, unspliced reads (that are not simply a result of an intron retention event), and therefore are largely uninformative as transcript models. As an example, in my case we see lots and lots and lots of genomic transcripts and reads from our single-nucleus long read approaches which we believe has to do with unprocessed RNA being enriched for in the nucleus vs. the cytosol. I'd check out [our publication](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02505-w) on sn long-read as well as [this publication](https://www.nature.com/articles/s41587-022-01231-3) which describes an exon capture addition to sn long-read protocols to help enrich for spliced (ie non genomic) transcripts vs. unspliced ones.

2. On the data used in the TALON manuscript, ~0.7% of the reads from the SIRV chromosomes were genomic. Code:

```python
import pandas as pd
df = pd.read_csv('GM12878_talon_read_annot.tsv', sep='\t')
df = df.loc[df.chrom.str.contains('SIRV')]
df = df[['read_name', 'transcript_novelty']].groupby('transcript_novelty').count()
total_reads = df.read_name.sum()
df['total'] = total_reads
df['perc'] = (df.read_name/df.total)*100
df
```

Output:
```
                    read_name  total       perc
transcript_novelty                             
Genomic                   145  21424   0.676811
ISM                      1361  21424   6.352689
Known                   19253  21424  89.866505
NIC                       379  21424   1.769044
NNC                       286  21424   1.334951
```

3. Genomic transcripts are monoexonic (ie contain no splice junctions) transcripts that lie within the annotated boundaries of a gene.

4. If TALON sees transcripts that are unspliced, they will be labelled genomic. If TALON sees transcripts that are partially spliced, there are a few different possibilities. If the unspliced intron is a retained intron that is noted in the reference annotation, the transcript will be known. If the unspliced intron is not in the reference annotation, it will be NNC. 

In any case, I think that it's worth taking another look at the novelty category figure:
<img width="458" alt="image" src="https://user-images.githubusercontent.com/21128281/168405616-d0596c18-7382-4a05-890f-fb60646547ee.png">

I also wanted to add that if you're looking for transcripts that contain splice junctions, genomic is not the novelty category you want to be looking at. I can't quite tell if that's what you're expecting from your post but figured I'd mention it.

Additionally, if you want to customize your filtering in such a way that is directly incompatible with TALON's filtering functions, it's usually not too difficult. If you pin down an additional class of transcripts or set of criteria you'd like to impose I'd be happy to help you write a script that will output a normal TALON pass list that you can then use with functions like `talon_abundance` and `talon_create_GTF`.

**Comment by callumparr** [comment]
Thanks for your reply.  Regarding what I am looking for, we are interested in generating some transcript models for RNA transcribed from enhancers regions during the differentiation of iPSC to neurons. I was told many enhancer regions are found within introns of coding and non-coding regions therefore they will overlap with known gene loci from gencode/Ensembl annotations but also not share any splicing or have no splicing. From my naive understanding, they will have independent transcription initiations, and read starts, rather than being generated from splicing of the coding gene they lie within. 

similar to this : 

https://iiif.elifesciences.org/lax/65161%2Felife-65161-fig1-v2.tif/full/1234,/0/default.webp 

For instance, if I look at some THP-1 data we have, we can see some reads from ssCAGE data that overlap with enhancers classified by two independents in silico methods. With our TALON we do not want to filter out. Allowing genomic when doing the filtering steps I thin retain these.

![F6_Interactome_TALON_THP-1_hg38_(modified)](https://user-images.githubusercontent.com/41637575/168538427-f0c9bd22-dcee-4e37-982d-bd5af0340baf.png)
![F6_Interactome_TALON_THP-1_hg38_(modified)-2](https://user-images.githubusercontent.com/41637575/168538436-6810f639-952d-40a0-8efc-0ba3f9c6a645.png)

**Comment by fairliereese** [comment]
In that case, I'd recommend taking your unfiltered abundance matrix and grabbing IDs for transcripts that are genomic and simply concatenating those IDs with an existing filtered pass list from TALON that you have. Here's some code to start:
```python
import pandas as pd

df = pd.read_csv('talon_abundance.tsv', sep='\t')
df = df.loc[df.transcript_novelty == 'Genomic']
df = df[['gene_ID', 'transcript_ID']]
df.to_csv('talon_pass_list.csv', sep=',', header=None, index=False, mode='a')
```

You can also modulate this call based on the expression of each isoform using the last columns of the abundance file, if you wish. But the output pass list file should be useable with all downstream utilities!

**Comment by callumparr** [comment]
Thank you I will try this.

**Comment by callumparr** [comment]
@fairliereese sorry to dig up an older issue. We have been working on trying to rescue some of these genomic novelty entries with what we think are genuine isoforms being initiated from within the intron region of a known gene. Still, likely we would want to class them as a new genes.  

>  From the raw transcript model, we first rescued the sense intronic RNA from the “Genomic” group. If the transcripts having their region non-overlapped with any of the known GENCODE exons, they were classed as “Intronic”. They were considered as novel genes and a novel gene ID (e.g. ONTG000000001) was assigned to each of them. Among the Intronic group, If the transcript region of them overlapped with another, ones were assigned with the same geneID. The update of  the gene ID was done from the raw transcript and these gene IDs were used after that. The remaining transcript models in the Genomic group show different levels of overlap with the GENCODE exons and contain intron sequences simultaneously. Their gene IDs remained as identified by TALON. The updated Genomic group, therefore, contains potentially novel isoforms, unprocessed transcripts or splicing intermediate of known genes. We have set stringent filtering criteria for the Novel isoform and Genomic groups

we've been looking through the create_GTF script wondering if there is a way to reassign an isoform we think based on some stringent filtering is a genuine isoform from a gene within an intron of another. 

We are wondering if it is also possible to update the TALON database to reflect our reassignments. How easy would this be using sqlite3. 

Say genomic TALONT XYZ was placed under Gene ID ENSGXZY but we now want to classify TALONT XYZ as TALONG XYZ. Also adding some other categories like 'intronic'  

Presumably, we need to update the boundaries of the original gene as well if we are removing isoforms.
