### ISSUE TITLE
ValueError: Exons of transcript  are not stored in ascending order.

### ISSUE THREAD

**Issue by gabee-chan** [mortazavilab/TALON#106]
Hi!! I'm trying to run the command `talon_initialize_database` with a GTF with only exons. I first use the command `talon_reformat_gtf` to format the GTF. Then, when I try running the `talon_initialize_database` I got the Error that the exons of the first transcript are not in ascending order but they are... Here is the exact error:
`Traceback (most recent call last):
  File "/share/ClusterShare/biodata/contrib/gabrod/anaconda2/envs/mypython38/bin/talon_initialize_database", line 33, in <module>
    sys.exit(load_entry_point('talon==5.0', 'console_scripts', 'talon_initialize_database')())
  File "/share/ClusterShare/biodata/contrib/gabrod/anaconda2/envs/mypython38/lib/python3.8/site-packages/talon-5.0-py3.8.egg/talon/initialize_talon_database.py", line 1005, in main
    genes, transcripts, exons = read_gtf_file(gtf_file)
  File "/share/ClusterShare/biodata/contrib/gabrod/anaconda2/envs/mypython38/lib/python3.8/site-packages/talon-5.0-py3.8.egg/talon/initialize_talon_database.py", line 532, in read_gtf_file
    currTranscript.add_exon(exon)
  File "/share/ClusterShare/biodata/contrib/gabrod/anaconda2/envs/mypython38/lib/python3.8/site-packages/talon-5.0-py3.8.egg/talon/transcript.py", line 116, in add_exon
    self.check_exon_validity()
  File "/share/ClusterShare/biodata/contrib/gabrod/anaconda2/envs/mypython38/lib/python3.8/site-packages/talon-5.0-py3.8.egg/talon/transcript.py", line 160, in check_exon_validity
    raise ValueError('Exons of transcript ' + \
ValueError: Exons of transcript ENSMUSG00000029638_transcript1 are not stored in ascending order.
`

Here is how my GTF looks:
![image](https://user-images.githubusercontent.com/14879053/178511486-3cf111bd-32e9-4dc8-9a3c-1d6a79d47e8c.png)

Looking at the script `transcript.py`, I notice that where the error "ValueError: Exons of transcript  are not stored in ascending order." there is a comment that says: **"# This error would indicate a TALON bug rather than user error, # so we shouldn't see it"**. 
Why am I seeing it?

Thanks for your help!

**Comment by fairliereese** [comment]
Hi there, would you mind hosting the GTF somewhere I can take download it? I will take a look and get back to you. My email is freese@uci.edu.

**Comment by fairliereese** [comment]
Actually, I didn't read your issue closely enough -- I see now that you're trying to use TALON on a GTF that has only exons. TALON does not natively support this but we do have a script that you can use to add gene and transcript entries to your GTF before running TALON. You can look for details on the script and how to run it [here](https://github.com/mortazavilab/TALON/wiki/Formatting-a-GTF-annotation-to-work-with-TALON). If this doesn't work please let me know and I can propose some other alternatives.

**Comment by gabee-chan** [comment]
Hi! Yes, as mentioned in the first post I used the `talon_reformat_gtf` for my GTF with only exons and get the GTF from the screenshot and I get the mentioned error. I emailed you the GTF with only exons in case the error starts from my GTF format.

Thanks!

**Comment by fairliereese** [comment]
Oh my gosh. I'm so sorry 🤦 I'll take another look into it. I should be able to get some code to you that will fix it.

**Comment by fairliereese** [comment]
Ok so actually, your exons are indeed not stored in ascending order. And I'm not sure how you can fix this because essentially you have exons within the same transcript that overlap other exons in the genes. I'm not sure how you made this GTF because this shouldn't be possible, as far as I am aware. This happens in multiple transcripts that you sent me. Here are some problematic coordinates to look at as reference:

```
ENSMUSG00000029638_transcript1: 8594071, 8592907
ENSMUSG00000030180_transcript1: 120406725, 120405860
ENSMUSG00000038538_transcript1: 38463741, 38464049
ENSMUSG00000071553_transcript1: 30544216, 30544135
ENSMUSG00000001518_transcript1: 128424931, 128422784
ENSMUSG00000001642_transcript1: 34309576, 34310635
```

I would carefully revisit how you are making your GTF to make sure it adheres to the proper structure / order.

**Comment by gabee-chan** [comment]
Hi, thanks for the help! I was able to format the GTF and now is running.
