### ISSUE TITLE
What database to use?

### ISSUE THREAD

**Issue by fergsc** [mortazavilab/TALON#114]
Hi,

I am attempting to annotate, using ONT RNA reads, a genome I have assembled. The species is very different from anything in all the public genome/gene databases. Is it appropiate to use a database thats evolutionary distance is very large?

Thanks.

**Comment by fairliereese** [comment]
Hi there, you should be able to run talon in "reference free" mode by initializing a talon database using an empty GTF. You just have to consider how stringently you filter your novel transcripts to create a new transcriptome, because by default all of your transcripts will be novel.

**Comment by fergsc** [comment]
Thanks, I shall run with out a reference gene set and see how the annotations and alinged RNA looks in IGV.
