### ISSUE TITLE
Error message : ValueError: SAM transcript 463c55e7-91c0-45cf-9630-122afc9a2267 lacks an MD tag

### ISSUE THREAD

**Issue by thadasps** [mortazavilab/TALON#117]
Hi, I use the data is adenovirus type 5 from nanopore and we can pass the step talon_initialize_database and labed_read but when we use the sam file to run step talon annotation. I got this error message
![image](https://user-images.githubusercontent.com/108725113/208951886-626a3fd1-8d39-4598-b91a-6f378da1ab5d.png)

Please advise me to solve this problem. Thank you

**Comment by yxsee** [comment]
From the Readme: 

> Please note that TALON requires the SAM MD tag, so Minimap2 should be run with the --MD flag enabled. In principle, you can use any other long-read alignment software provided that an MD tag is generated.
