### ISSUE TITLE
Single cell reads appear to be unlabelled when filtering transcripts

### ISSUE THREAD

**Issue by yxsee** [mortazavilab/TALON#121]
I'm having trouble filtering transcripts on a single cell long read dataset. I ran `talon_filter_transcripts` with `--minDatasets 5 --minCount 1` and got the following error for all datasets:
`Reads in dataset NNNNNNNNNNNNNNNNNNNNNNNN appear to be unlabelled. Only known transcripts will pass the filter.`
Running` talon_filter_transcript` on the same dataset as a pseudo-bulk sample did not result in this error. Thanks in advance for help with troubleshooting this!

**Comment by fairliereese** [comment]
Did you use the `--cb` option for your single-cell TALON run? Where did you label your cell barcodes in your input dataset?
