### ISSUE TITLE
How to visualize custom gtf?

### ISSUE THREAD

**Issue by thadasps** [mortazavilab/TALON#122]
I use the SIRV file that you provide in the tutorial. So in your paper mention that use ucsc genome browser to visualize the custiom gtf file. Can you point me to how to visualize in ucsc or any tools? because when I try to use ucsc that I get error in the picture.

I am a beginner in bioinformatics. So sorry
 
![image](https://user-images.githubusercontent.com/108725113/212046342-f2bd0982-f9c2-40a8-a2c2-010720bbf52e.png)

**Comment by fairliereese** [comment]
Hi, you're going to want to drop everything in your GTF that comes from a SIRV or ERCC chromosome. Here's some code to do it in Python:

```python
import pyranges as pr

df = pr.read_gtf('input.gtf', duplicate_attr=True).as_df()
df = df.loc[~df.Chromosome.str.contains('SIRV')]
df = df.loc[~df.Chromosome.str.contains('ERCC')]
df = pr.PyRanges(df)
df.to_gtf('output_no_sirv_ercc.gtf')
```
