### ISSUE TITLE
operand type error in talon_initialize_database

### ISSUE THREAD

**Issue by m-noonan** [mortazavilab/TALON#123]
I'm getting this error when running talon_initialize_database:

File "/home/users/mnoonan/.local/lib/python3.8/site-packages/talon/initialize_talon_database.py", line 984, in main
    db_name = outprefix + ".db"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by KristinaGagalova** [comment]
Hi, 
Could you please provide more details about the run? Was this issue solved?
