### ISSUE TITLE
talon_filter_transcript --minCounts with --maxFracA

### ISSUE THREAD

**Issue by callumparr** [mortazavilab/TALON#125]
I wanted to clarify that if we assign --minCounts and --minDatasets (e.g two replicates) but I keep the default for maxFracA. 

I had assumed that if any read supporting a model has > 0.5 As following it then this model would be dumped regardless of whether both replicates at least 5 reads. 

I saw a model that has 7 and 5 counts in rep1 and rep2 respectively but it doesn't output to whitelist, I then checked the read annotation file and indeed some of the reads have fractionA > 0.5 meaning one of the replicates only have 4 reads not 5 therefore only one of the replicates satisfies all criteria and the model is not output. 

Is this correct? 

And do these filtering only apply to TALONT? What about ENST? Are all ENST models with a least a read in any dataset output to the whitelist despite the use of --minCounts and --minDatasets ? I guess this would make sense, so long as its expressed in the dataset there would be no reason to filter out.

**Comment by fairliereese** [comment]
The filtering options create intersections of novel transcripts to output for the pass list, not unions. So yes, if you filter your transcripts using all three of those options, you will only get transcripts that satisfy all three criteria. And yes, TALON only filters novel transcript models, not known models that are annotated in the reference you used.

If you want to start making custom pass lists I would suggest trying to run the filter separately and performing the type of join you prefer on the resultant lists. As long as the pass list that you provide to the abundance and GTF utilities follows the same format as the output from the TALON filter, you can use whatever!
