### ISSUE TITLE
fail to extract CB field

### ISSUE THREAD

**Issue by kunxiong** [mortazavilab/TALON#127]
I noticed that talon sometimes has problem extracting the CB field:

talon --cb --f config.csv --db talon_minReads_5.db --threads 4 --build mm10 --o talon_swan

 /home/s.kun.xiong/bin/miniconda3/envs/my_R/lib/python3.8/site-packages/talon/talon.py:1523: FutureWarning: Defining usecols with out of bounds indices is deprecated and will raise a ParserError in a future version.
  df = pd.read_csv(curr_sam, sep='\tCB:Z:', comment='@',

Traceback (most recent call last):
  File "/home/s.kun.xiong/bin/miniconda3/envs/my_R/bin/talon", line 8, in <module>
    sys.exit(main())
  File "/home/s.kun.xiong/bin/miniconda3/envs/my_R/lib/python3.8/site-packages/talon/talon.py", line 2579, in main
    sam_files, dset_metadata = check_inputs(options)
  File "/home/s.kun.xiong/bin/miniconda3/envs/my_R/lib/python3.8/site-packages/talon/talon.py", line 1527, in check_inputs
    raise RuntimeError(
RuntimeError: SAM/BAM file contains no CB tags

Below is the sam file that generated the error:

@SQ	SN:chr10	LN:130694993
@SQ	SN:chr11	LN:122082543
@SQ	SN:chr12	LN:120129022
@SQ	SN:chr13	LN:120421639
@SQ	SN:chr14	LN:124902244
@SQ	SN:chr15	LN:104043685
@SQ	SN:chr16	LN:98207768
@SQ	SN:chr17	LN:94987271
@SQ	SN:chr18	LN:90702639
@SQ	SN:chr19	LN:61431566
@SQ	SN:chr1	LN:195471971
@SQ	SN:chr2	LN:182113224
@SQ	SN:chr3	LN:160039680
@SQ	SN:chr4	LN:156508116
@SQ	SN:chr5	LN:151834684
@SQ	SN:chr6	LN:149736546
@SQ	SN:chr7	LN:145441459
@SQ	SN:chr8	LN:129401213
@SQ	SN:chr9	LN:124595110
@SQ	SN:chrM	LN:16299
@SQ	SN:chrX	LN:171031299
@SQ	SN:chrY	LN:91744698
@PG	ID:minimap2	PN:minimap2	VN:2.24-r1122	CL:minimap2 -t 16 --MD -ax splice -uf -k14 /home/s.kun.xiong/cross_node/annotation/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/Chrs.fa /home/s.kun.xiong/cross_node/scRNA_splicing/umi/stringent_extracted_rc_no_polyA.fastq
aedc7aef-7810-4c25-80ee-6810fe0c3d57_ACCATTTCATCCTATT_CGCTAGCACAGT	0	chr11	104327755	60	503M1I2M1D9M1D5M1D3M1D137M	*	0	0	GATATCTGAGTTCAAGGTCATCCTGGTCTATAAAACAAGATCCAGGACATCCAGAGCTACACAGAGAAACCCTGTCTTAAAAACACAAAAAATGAATGAACGAATGAACGAACGAACGAACGAACGAATGAATGAATGAATGAATGTTTTCCTCCCACCACAGACTAGCTCTGGTGTATAGAACCTTATCATTAATCTCACTCTCTACATCTTGCAGATTGAAACCCACAAGCTGACCTTCAGGGAGAATGCCAAAGCCAAGACAGACCATGGAGCAGAAATTGTGTATAAGTCACCCGTGGTGTCTGGGGACACATCTCCACGGCACCTCAGCAATGTGTCTTCCACGGGCAGCATCGACATGGTGGACTCACCACAGCTTGCCACACTAGCCGATGAAGTGTCTGCTTCCTTGGCCAAGCAGGGTTTGTGATCAGGCTCCCAGGGCAGTCAATAATCATGGAGAGAAGAGAGAGTGAGAGTGTGGAAAAAAAAAAAAAAAATAGGTGCTAAGGCTCTTCCCCTGCCCTCCCCGCTGCTCCTCATAGACAGGCTGACCTGCTTGTCACCTAACCTGCTTTTGTGGCTCGGATTTGGCTCGGGACTTCAAAATCAGTGATGGGAAAAGTACATTTCATCTTTCCAAATTGATTTGTGGGC	9;::<5311/.//567?CA@@@<<;99;;=@BIJEFD?>?>=>>>=>>=?>=66>==;;<=>@<<<<=A@>;;;;;92(((),CA=0///GIF><==<?>85555:;::;;::<=><<<<<>@><;<<<?A?<=@?><@??=<98889966865663:<==>:977779:<;;;;<>>?>556??<<98:;<BBDA>??><=<<=F=>>?@?A@?@?>>>=?@A?====?B@>???@??=,,,,,<<==<;:::<=BBAA@ABCC@@>>>??>>==>BBEFGEFDBA?>>>>?AAA?;88889<<<===>=@?@AAB>?;987344+****445>A@AAA@??@@@B?87778<<<<60//01C??=;;;;==<=>?A=<<>=::;;<B@@>>97788=EA=====>CCB=;;;>@@@@@BA@?>==>??A@AABA?===>@?9?<<<<=@@AAA@@A@@@@?@A@EF=<;;C{{D>=====;<903:=BJJJ?410/--)&&&&&&&&'%%%&'&&&&&),-0.12546=<<<9999:;;;;==>>>>??@@??@@><;;;<??>>=<9999:???>?CEGFA>:9:;:<==AE?<;;;65555=>ACFJIJIKFDCEDC=<<=>ON@?>?ACCGEJDD@CAB<=DEFDBABB@@;644	NM:i:10	ms:i:629	AS:i:629	nn:i:0	ts:A:+	tp:A:P	cm:i:198	s1:i:622	s2:i:44	de:f:0.0151	MD:Z:505^A0A2A1C0T2^C1C3^G3^T137	rl:i:98	jM:B:c,-1	jI:B:i,-1	fA:f:0.6	CB:Z:ACCATTTCATCCTATT

The QUAL field of the read prevents pd.read_csv from finding the delimiter "\tCB:Z:". Since this is the first read, talon complains that it cannot find the CB tag, which is the second column from pd.read_csv. If the QUAL field of the first read is empty, i.e. "*", then the read is parsed correctly and talon does not complain about anything. The problem is that if the sam file also contains reads with non-empty QUAL, then the cell barcodes of these reads will be marked as none, which can cause troubles in the downstream analysis. Perhaps there should be a step that sets all QUAL fields of the input sam to empty?

**Comment by fairliereese** [comment]
Hi there, thank you for bringing this to my attention. Can you please try again using the latest commits?

**Comment by kunxiong** [comment]
Hi, thank you for updating talon! The new script parsed my sam file correctly.
