### ISSUE TITLE
What should I do if I have reads that are reverse complement to the original RNA sequences?

### ISSUE THREAD

**Issue by hd00ljy** [mortazavilab/TALON#128]
My long reads are from the 1st strand of the cDNA.

This means it goes as follows.

5'-TTTTTTTTTTTTAGTATCGTA-3'
         (polyT)

Could you help me with this? Will there be solutions other than reverse complementing the original fastq file?

**Comment by callumparr** [comment]
What kit did you use ? For Nanopore cDNA kits you can use pychopper to orientate the reads as well as trim the adapters. If you are using custom adapters/primers pychopper can also be used with some tuning. Or you might try this tool https://gitlab.com/mcfrith/primer-chop. It also trims long polyA runs. 

If you used PacBio I’m guessing they have similar tools after generated the collapse CCS/HiFi reads

**Comment by hd00ljy** [comment]
Thank you for your reply, it seems no quantification tool provide strand options for long read.

I should try reverse complementing the raw read sequences.
