### ISSUE TITLE
NameError: name 'vertex_counter' is not defined

### ISSUE THREAD

**Issue by Kiliankleemann** [mortazavilab/TALON#137]
Tried to run TALON with the following command:
mkdir TALON_output
talon  --f config.csv \
       --db hg38.db \
       --build hg38_rmsk_ucsd \
       --threads 4 \
       --o TALON_output/

but I got this error:
Traceback (most recent call last):
  File "/Users/kiliankleemann/anaconda3/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/kiliankleemann/anaconda3/lib/python3.11/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kiliankleemann/anaconda3/lib/python3.11/site-packages/talon/talon.py", line 2333, in parallel_talon
    annotation_info = annotate_read(record, cursor, run_info,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kiliankleemann/anaconda3/lib/python3.11/site-packages/talon/talon.py", line 2514, in annotate_read
    annotation_info = identify_monoexon_transcript(chrom, positions, strand,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kiliankleemann/anaconda3/lib/python3.11/site-packages/talon/talon.py", line 1817, in identify_monoexon_transcript
    vertex_IDs, v_novelty, diff_5p, diff_3p = match_monoexon_vertices(
                                              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kiliankleemann/anaconda3/lib/python3.11/site-packages/talon/talon.py", line 193, in match_monoexon_vertices
    vertex_match = create_vertex(chromosome, position, location_dict, run_info)[
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kiliankleemann/anaconda3/lib/python3.11/site-packages/talon/talon.py", line 416, in create_vertex
    new_ID = vertex_counter.increment()
             ^^^^^^^^^^^^^^
NameError: name 'vertex_counter' is not defined

**Comment by fairliereese** [comment]
Hi there, can you please let me know what version of TALON you're running?

**Comment by Kiliankleemann** [comment]
talon                     5.0                      pypi_0    pypi

**Comment by Kiliankleemann** [comment]
It seems to initiate properly but then fails: 

[ 2023-10-11 13:41:18 ] Started TALON run
[ 2023-10-11 13:42:27 ] Merged input SAM/BAM files
[ 2023-10-11 13:43:03 ] Split reads into 305 intervals
[ 2023-10-11 13:43:05 ] Launching parallel annotation jobs
[ 2023-10-11 13:43:05 ] Annotating reads in interval GL000009.2:116008-116358...
[ 2023-10-11 13:43:05 ] Annotating reads in interval GL383522.1:57520-77044...
[ 2023-10-11 13:43:05 ] Annotating reads in interval GL383582.2:2045-71551...
[ 2023-10-11 13:43:05 ] Annotating reads in interval GL000194.1:44042-106555...

**Comment by fairliereese** [comment]
It looks like you are having the same issue as in #136, vaguely. I noticed that you're both using Python >= 3.10. Digging into this, it looks like the behaviour of sharing these "counter" variables between multiprocessing threads has changed (see https://stackoverflow.com/questions/70552775/multiprocess-inherently-shared-memory-in-no-longer-working-on-python-3-10-comin). Maybe you could try downgrading your Python version. I will likely try to update the requirements in the `setup.py` file to solve this in the future, once I've done some testing on my end.

**Comment by Kiliankleemann** [comment]
Thanks so much for the reply. Ill try it now.

**Comment by fairliereese** [comment]
Just to follow up, I tested this behavior and found that I was able to reproduce your issue with Python >= 3.8, as the Stackoverflow thread I found suggested. I have now included <3.8 as a Python dependency in the installation requirements in the latest [release](https://github.com/mortazavilab/TALON/releases/tag/v6.0). Please try installing with this version and see if this fixes your issue!
