### ISSUE TITLE
Question - merging TALON databases

### ISSUE THREAD

**Issue by kathryncrouch** [mortazavilab/TALON#141]
Hi,

We have multiple TALON databases generated from different input datasets. These have been generated using the same reference annotation.

Is there some way that we can obtain the union of all the TALON predictions from all the different datasets?

I know we could generate one large database, but at the scale we're working at, that's going to either create a bottleneck or potentially cause race conditions in our pipeline, so we're looking for an alternative solution. I feel like merging the databases would potentially be cleaner than dumping out and merging GTF files.

**Comment by fairliereese** [comment]
Unfortunately there is no way to merge individual TALON databases and no plan to develop such a tool. However, we too are dealing with datasets whose scale has outgrown TALON, and have been using another tool developed in the lab, [Cerberus](https://mortazavilab.github.io/cerberus/html/index.html), to merge TALON results using a unified reference of 5' ends, intron chains, and 3' ends. This does, however, rely on the intermediate GTF file output from TALON.
