### ISSUE TITLE
internal priming on PCS111 cDNA kit

### ISSUE THREAD

**Issue by MustafaElshani** [mortazavilab/TALON#143]
The nanopore PCS111 kit library preparation kit effectively binds to the end of polyA tails and has no issue with internal priming as with previous PC109 kits .

In this case will it be required for `talon_label_reads` to be run to use TALON downstream?
What will the effect be if reads are not labelled ?

Mustafa

**Comment by fairliereese** [comment]
I have no sense of how well this kit works. I would recommend maybe filtering both ways (you can use the same TALON run if you did run `talon_label_reads` and comparing your calls to see what your prefix ISM rate is with and without the internal priming filter setting in `talon_filter_transcripts`.
