### ISSUE TITLE
Antisense after pychopper minimap2. to -uf or not -uf

### ISSUE THREAD

**Issue by MustafaElshani** [mortazavilab/TALON#144]
I run TALON on data after pychopper and use minimap2 to generate `.sam` as follows

`minimap2 -ax splice -t 40 --MD GRCh38.primary_assembly.genome.fa --junc-bed gencode.v41.primary_assembly.annotation.bed ../../fastq/"${sample}"_full_length.fastq > ../../alignments/TALON/"${sample}".sam `

However I do get around ~40% antisense reads, I presumed pychopper orientated the reads 5'->3'. Do I need to add `-uf` on minimap2

**Comment by fairliereese** [comment]
Internally, we have to flip ONT reads manually. I do not believe PyChopper does. You will need to orient your reads from 5'->3' before running TALON.
