### ISSUE TITLE
talon_label_reads: AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by ashokpatowary** [mortazavilab/TALON#54]
Hi @dewyman 

I just updated to TALON v5 and tried to reprocess one of my old data. So, we I tried talon_label_reads on my data I am getting the following error. The same sam file was processed earlier with v4.4 without any error. Can you please look into it?

Thanks

[ 2020-03-23 02:00:23 ] Splitting SAM by chromosome...
[ 2020-03-23 02:00:23 ] -----Converting to bam....
[ 2020-03-23 02:00:51 ] -----Sorting and indexing...
[ 2020-03-23 02:01:34 ] -----Writing chrom files...
[ 2020-03-23 02:02:44 ] Launching parallel jobs...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/u/local/apps/python/3.7.2/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/u/local/apps/python/3.7.2/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/u/home/a/ashokpat/.local/lib/python3.7/site-packages/talon/talon_label_reads.py", line 189, in run_chrom_thread
    one_based_attributes=False)
  File "/u/home/a/ashokpat/.local/lib/python3.7/site-packages/pyfaidx/__init__.py", line 999, in __init__
    build_index=build_index)
  File "/u/home/a/ashokpat/.local/lib/python3.7/site-packages/pyfaidx/__init__.py", line 333, in __init__
    if filename.lower().endswith('.bgz') or filename.lower().endswith(
AttributeError: 'NoneType' object has no attribute 'lower'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/u/home/a/ashokpat/.local/bin/talon_label_reads", line 11, in <module>
    load_entry_point('talon==5.0', 'console_scripts', 'talon_label_reads')()
  File "/u/home/a/ashokpat/.local/lib/python3.7/site-packages/talon/talon_label_reads.py", line 280, in main
    pool.starmap(run_chrom_thread, jobs)
  File "/u/local/apps/python/3.7.2/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/u/local/apps/python/3.7.2/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by dewyman** [comment]
Hi Ashok, 
I think your SAM file is fine. Did you provide the required Fasta reference genome file though? It looks like pyfaidx is trying to open a nonexistent file path. You can see all the options by running talon_label_reads --h.
Best,
Dana

**Comment by ashokpatowary** [comment]
Hi @dewyman 

Yess I did provide the genome fasta file.

talon_label_reads  --f=TransClen_SJ_HFB_clean_h.sam --g=GRCh37.primary_assembly.genome_mod.fa  --t=12 --deleteTmp --o label

**Comment by dewyman** [comment]
Ok good. And you've doubled-checked that the SAM path and fasta paths are correct?

**Comment by ashokpatowary** [comment]
@dewyman Yes. the paths are correct. I again tried with full path to sam and fa files. Still same error.

**Comment by dewyman** [comment]
Thanks for checking that for me! Just trying to rule out the most basic possible reasons before we go to the more labor-intensive things :) 
Would you mind trying to run talon_label_reads on the provided TALON example [here](https://github.com/mortazavilab/TALON/tree/master/example) for me with the same settings you are using now? If that works, then we'll want to see if there is an issue with your input files. If it does not work, then we probably have an installation/package version issue.

**Comment by ashokpatowary** [comment]
hi @dewyman 

Thanks and you are right while asking me to checks those minor things. As a user community that's our responsibility.  So, the problem is solved and here is the issue. While giving the options like --f, --g for the example dataset it works perfect in either way like --f *.sam or --f=*.sam and --g *.fa or --g=*fa. But for my dataset it works only when I give --f *.sam --g *.fa  and not like --f=*.sam --g=*fa. So, its a {space} vs {=} issue. Anyways thanks.

**Comment by dewyman** [comment]
Hi Ashok,
I'm glad you were able to figure it out! As always, I'm happy to answer questions if you run into any other issues.
Best,
Dana
