### ISSUE TITLE
Can't run talon_abundance - annotation missing?

### ISSUE THREAD

**Issue by wolfgangrumpf** [mortazavilab/TALON#57]
I created a database using this command:

talon_initialize_database --f gencode.v33.annotation.gtf --g GRCh38.99 --a GRCh38.99 --o GRCh38.99.fam02

I was able to execute talon and talon_summarize just fine.  I then tried to get the abundance data with:

talon_abundance --db GRCh38.99.fam02.db -b GRCh38.99.fam02 --annot gencode.v33 --o fam02

But I got the error that the annotation wasn't in the database.  What am I doing wrong?

**Comment by fairliereese** [comment]
Hey, it looks like you're calling your annotation "GRCh38.99" when you initialize your database, but then calling it "gencode.v33" when trying to  make your abundance file. Instead, please use "GRCH38.99" as your --annot value when running talon_abundance. Let me know if this works!

**Comment by wolfgangrumpf** [comment]
Yup, that did it.  Thanks!  I'm still trying to work my way through TALON, I appreciate the help!

**Comment by fairliereese** [comment]
Glad to hear it! We can update the documentation accordingly so others don't experience this confusion. Thanks for bringing this to our attention!
