### ISSUE TITLE
How can I get transcript start/end sites in output?

### ISSUE THREAD

**Issue by wolfgangrumpf** [mortazavilab/TALON#58]
I read the instructions and it says:

Start_support: If the user provided a custom SAM flag (tS:Z) to denote external evidence for the start site of a read, the value will be shown here.
End_support: If the user provided a custom SAM flag (tE:Z to denote external evidence for the end site of a read, the value will be shown here.

I'm not sure how to go about getting that data into the SAM file - any recommendations appreciated!

**Comment by dewyman** [comment]
Hi Wolfgang,

Thank you for your question! These custom SAM flags are an optional beta feature for users. Basically, if you have some method of your own that determines start/end support of individual reads, you would add your tag in the format shown to the SAM reads prior to running TALON, and then that information would show up in the TALON database and read_annot file, where you could use it to generate custom whitelists for filtering. 

In the future, we anticipate adding a check for start and end support to the talon_label_reads step that would accept a bed file of known starts and/or ends from the user and apply this to check the start and end of each read. But we have not had the chance to implement this yet.

Best,
Dana

**Comment by wolfgangrumpf** [comment]
Wouldn't it be possible to extract this info from the GTF file used to create the database?  That way you could have talon compute the distance from transcription start/transcription end for each transcript quickly...

**Comment by dewyman** [comment]
Hi Wolfgang,
Yes, I think that would in principle be possible to implement for known transcripts. What TALON currently does is record the distance to the nearest 5' or 3' end for each individual read (this is recorded in the database's 'observed' table as the start_delta and end_delta fields). The caveat is that even for known trancripts, this nearest point may not necessarily be the start or end point of the matching GENCODE model. So it is a little more convoluted than we would like, and something we may try to improve in the future. 

In the meantime, I think the best course of action for people interested in the 5' and 3' ends specifically is to use the read annotation file. This file records the start and end of every individual read along with its gene and isoform assignment, so it's a good starting point for looking at how much variation there might be at the 5' or 3' end for a gene/isoform of interest.

Best,
Dana
