### ISSUE TITLE
fusion transcript?

### ISSUE THREAD

**Issue by ashokpatowary** [mortazavilab/TALON#60]
Hi @dewyman @fairliereese 

Will it be possible to identify all the fusion transcripts in the data using talon?

Thanks

**Comment by fairliereese** [comment]
Hi there, sorry for the late response but TALON does not detect fusion transcripts.

**Comment by ashokpatowary** [comment]
@fairliereese Thanks. Just another simple query. Does talon detect novel exon upstream of the gene start site (i.e novel exon splicing to the 1st exon of the known gene transcripts)? or talon identified exons within the reference gene boundary only?

Thanks

**Comment by fairliereese** [comment]
If TALON finds a new exon upstream of the annotated TSSs belonging to the gene, the transcripts will be annotated as novel but still should belong to the gene as the rest of the splicing structure is shared between the gene and the transcript.
