### ISSUE TITLE
talon_get_sjs

### ISSUE THREAD

**Issue by ashokpatowary** [mortazavilab/TALON#61]
Hi @dewyman @fairliereese 

Cab you look into this error

Command:
`talon_get_sjs --gtf merge_talon.gtf --db merge.db  --ref gencode.v33lift37.annotation_ap.gtf --outprefix merge`

error

`Traceback (most recent call last):
  File "/u/home/a/ashokpat/project-gandalm/Tools/TALON/src/talon/post/get_transcript_sjs.py", line 442, in <module>
    main()
  File "/u/home/a/ashokpat/project-gandalm/Tools/TALON/src/talon/post/get_transcript_sjs.py", line 413, in main
    args = get_args()
  File "/u/home/a/ashokpat/project-gandalm/Tools/TALON/src/talon/post/get_transcript_sjs.py", line 33, in get_args
    raise Exception('only input gtf or db')
Exception: only input gtf or db`

command:
`talon_get_sjs --gtf merge_talon.gtf --ref gencode.v33lift37.annotation_ap.gtf --outprefix merge`

error

`Traceback (most recent call last):
  File "/u/home/a/ashokpat/project-gandalm/Tools/TALON/src/talon/post/get_transcript_sjs.py", line 442, in <module>
    main()
  File "/u/home/a/ashokpat/project-gandalm/Tools/TALON/src/talon/post/get_transcript_sjs.py", line 415, in main
    ref_loc_df, ref_edge_df, ref_t_df = create_dfs_gtf(args.ref_gtf)
  File "/u/home/a/ashokpat/project-gandalm/Tools/TALON/src/talon/post/get_transcript_sjs.py", line 182, in create_dfs_gtf
    entry_type = line[2]
IndexError: list index out of range`

Do let me know if you need any further information.

**Comment by fairliereese** [comment]
So the first problem is because you provided both the --db and the --gtf arguments when you only need one, as you might have figured out. For the other error, it looks to me like it's complaining about your reference gtf and how is formatted. Could you send it to me? freese@uci.edu

**Comment by ashokpatowary** [comment]
@fairliereese 

Ref gtf file was downloaded from here ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_33/GRCh37_mapping/gencode.v33lift37.annotation.gtf.gz

Its too big to send through mail.

Thanks

**Comment by fairliereese** [comment]
Oh no, is this the same gtf that was giving us trouble before? I will look into it when I have time!

**Comment by ashokpatowary** [comment]
@fairliereese Yes. The same one.

**Comment by ashokpatowary** [comment]
@fairliereese 
Can we make --gft optional?

**Comment by fairliereese** [comment]
Do you mean make --ref or --gtf optional? I could make --ref optional for those that are not interested in the novelty of their splice junctions. For --gtf, this utility has to use either --gtf or --db. In that sense it is optional, as long as you use the --db option. 

Either way, I determined that the issue with running this tool is that the reference gtf has a header format that I adjusted the software to account for in other utilities, but the fix didn't make its way into this utility yet. I just pushed a fix to it though, so if you do a fresh clone and install, you should be able to run that second command there now.

**Comment by ashokpatowary** [comment]
@fairliereese 
The script is running over 24 hour till now. Does it supposed to take such a long time??

Also I am having another query. I was going through the gtf file produced by TALON and come across many exon for which start and end position is same. I did not understand why. Please the the 1st exon start and end in the image attached. Thanks.
<img width="1206" alt="Screen Shot 2020-04-18 at 3 46 20 PM" src="https://user-images.githubusercontent.com/42618005/79673183-cb092480-818c-11ea-9dc8-0d0a7a6ddc41.png">

**Comment by fairliereese** [comment]
So I've seen the single-base exon issue crop up before and at this point I'm not exactly sure why it happens. What version of TALON did you run to call your transcript isoforms, and what exactly were the arguments you passed to it?

With regards to the runtime of the splice junction code, it should not be running that long.... In fact we've already optimized it once after deciding it was running too long the way it was previously written. If you wouldn't mind, I'd be interested in seeing your TALON gtf, and the command you used to generate the gtf from the TALON database.

**Comment by ashokpatowary** [comment]
@fairliereese 

I think I am using v5.0 of TALON.

my command is 
`talon_create_GTF --db merge.db -b hg37 -a gencode_v33 --whitelist whitelist_multiexon.txt --o merge &`

For `talon_get_sjs` I just updated the TALON repo and ran it yesterday. My command was
`talon_get_sjs --gtf merge_talon.gtf --ref gencode.v33lift37.annotation.gtf --outprefix merge`

**Comment by fairliereese** [comment]
Thank you! 

I've found the bottleneck in the splice junction code. I think it's something I'm going to have to discuss with @dewyman, but she is busy with defense things! As a temporary measure, if you want me to give you a version of the code that will give you the splice junctions but not the transcript ids that use them, I can. Let me know!

**Comment by ashokpatowary** [comment]
@fairliereese 

No hurries. Take you time and let @dewyman defense her thesis. For now as a stop gap arrangement I used `get_SJs_from_gtf.py` from TranscriptClean.

**Comment by fairliereese** [comment]
Smart! I will let you know when I have an update fro you.
