### ISSUE TITLE
TALON gene abundance

### ISSUE THREAD

**Issue by ashokpatowary** [mortazavilab/TALON#62]
Hi @dewyman @fairliereese 

I was trying to get abundance genes identified in my dataset. So, I tried it by

`talon_abundance --db Iso_.db -a gencode_v33 -b hg37 --o GeneAbundance` 

Since it was supposed to generate gene wise abundance I was expecting per gene one entry in the output file. But I can multiple entry per gene. How can I generate a one gene one entry abundance file?

Thanks

**Comment by fairliereese** [comment]
The abundance files that TALON creates are expression values on the transcript-isoform level. To get gene-level expression values, you can use your favorite spreadsheet editor or table manipulation programming library (ie Pandas in Python or dplyr in R) to add up the counts for each row with the same gene ID (either column 1 or 3, both would work). This is also possibly another option we could add to the abundance file script. If you need more specific help, feel free to email me.

**Comment by ashokpatowary** [comment]
@fairliereese Thanks for response. I misread the statement from the TALON description 

`To generate a file suitable for gene expression analysis, skip the --whitelist option (i.e. make an unfiltered abundance file)`

Since I am trying to used TALON to single cell data I was also looking for gene level expression/ abundance to compare with short read clustering.

Thanks

**Comment by fairliereese** [comment]
This option still won't give you gene-level expression unfortunately, it will just exclude specific transcript models from the final abundance file. Again, if you need my help figuring out how to aggregate the counts across genes I will be more than happy to work with you.

**Comment by ashokpatowary** [comment]
@fairliereese Thanks for your offer for help. I just followed your suggestion of adding up the counts for each row with the same gene ID and generated an abundance file. Being a molecular biologist I am not good in scripting language of R or python. But I enjoyed working with awk; so just wrote an awk script for the same. Thanks and for the advice and also for your offer to help.

**Comment by fairliereese** [comment]
Of course! I think this would be a valuable option to add in the future to our abundance script so thank you for bringing it to our attention, and kudos to you for figuring out how to reformat your table the way you want it!
