### ISSUE TITLE
talon_read_annot.tsv: known

### ISSUE THREAD

**Issue by ashokpatowary** [mortazavilab/TALON#64]
Hi @dewyman @fairliereese 

I am having a query regarding known status for an transcript in the *read_annot.tsv file. What I understand, known are transcripts with full splice match with the reference gtf file (in my case gecodev33). Now please have a look in the following example. You can see talon marked it Known

<img width="1274" alt="Screen Shot 2020-06-07 at 11 02 51 AM" src="https://user-images.githubusercontent.com/42618005/83976587-bce3a480-a8af-11ea-8638-a323dcc7873f.png">

But, when I checked with the reference annotation file I can see that actually its  an ISM. 

<img width="1269" alt="Screen Shot 2020-06-07 at 11 03 14 AM" src="https://user-images.githubusercontent.com/42618005/83976603-dbe23680-a8af-11ea-861d-35e9a4299dd9.png">

Did I misunderstood something here? 

Thanks

**Comment by fairliereese** [comment]
Hi.
All transcripts that map to the reference annotation you provide TALON will be categorized as known transcripts. This means that every transcript in the reference annotation you use (in this case GENCODE v33), will also be known transcripts, regardless of any labelling they have in the reference. Moreover, I don't see anywhere in your screenshot of the GTF entry that it says it is an ISM. I'm not sure what you are concerned about.

**Comment by ashokpatowary** [comment]
@fairliereese 

Ok. I got it now. Thanks. My concern was that for the transcript id ENST00000533608.6_2 the reference transcript position is chr11:44117228-44273531. But in the *.tsv file when I extract the reads for which the annot_transcript_id is "ENST00000533608.6_2" None of them are matching full length (in this case end position is much upstream). What I understand from this image was 
that this should not be labeled as Known. 

<img width="405" alt="test" src="https://user-images.githubusercontent.com/42618005/83978852-1e5f3f80-a8bf-11ea-9942-27f19575206d.png">

Thanks

**Comment by fairliereese** [comment]
TALON only only considers splice junctions, not read starts and ends, to assign a read to a transcript. In this way, transcript starts and ends are flexible.
