### ISSUE TITLE
Error in get_read_annotations.py

### ISSUE THREAD

**Issue by abs-yy** [mortazavilab/TALON#65]
Hi, thanks for the brilliant software!
I've been trying TALON (installed through pip in a condo env), but I am getting an no-strand error at the annotation output stage.

% talon --db genome.fasta.talon.db  --build genome.fasta --thread 62  --o=talon --f=talon_config

```
[ 2020-06-09 04:15:41 ] Creating read-wise annotation file.
<sqlite3.Row object at 0x7f65f317e4b0>
Traceback (most recent call last):
  File "/home/abs/anaconda3/envs/talon/bin/talon", line 8, in <module>
    sys.exit(main())
  File "/home/abs/anaconda3/envs/talon/lib/python3.6/site-packages/talon/talon.py", line 2472, in main
    outprefix, datasets = datasets)
  File "/home/abs/anaconda3/envs/talon/lib/python3.6/site-packages/talon/post/get_read_annotations.py", line 358, in make_read_annot_file
    fetch_reads(database, build, tmp_file = tmp_read_file, datasets = datasets)
  File "/home/abs/anaconda3/envs/talon/lib/python3.6/site-packages/talon/post/get_read_annotations.py", line 118, in fetch_reads
    raise ValueError("Unrecognized strand value: " + str(strand))
ValueError: Unrecognized strand value: None
```

Is there something that I can do to solve this problem?

Thanks.

**Comment by fairliereese** [comment]
Hi,
This is an error that I have never seen before. Did TALON give you an output database or did it throw this error before that?

**Comment by abs-yy** [comment]
It just died right here without other errors.

**Comment by abs-yy** [comment]
I've tried the SQL query against the db file at DB Browser for SQLite in my local computer but it worked out fine, is there any requirement in the Sqlite version?

**Comment by fairliereese** [comment]
I'm not sure if there are sqlite version incompatibilities. My environment that I'm able to run TALON from has sqlite3 (the Python library) version 2.6.0, and sqlite version 3.30.1. What versions do you have? You can check easily from Python with:
 
```python
import sqlite3
print(sqlite3.version)
print(sqlite3.sqlite_version)
```

**Comment by fairliereese** [comment]
Also your database should be completely populated now, after looking at the code... You can try to do some downstream analysis if you feel up to it but of course I would be skeptical of the integrity of the database.

**Comment by fairliereese** [comment]
It looks like one of your genes does not have a strand associated with it, which is what is directly causing this issue. It is possible in that case that your reference GTF might be missing a strand field.

**Comment by abs-yy** [comment]
Thanks for the info

I've checked the gtf file but there are no strand information missing genes. 
The SQLite versions were also close to your environments.
>>> import sqlite3
>>> print(sqlite3.version)
2.6.0
>>> print(sqlite3.sqlite_version)
3.28.0

would it be possible to output a gtf file from the database using the talon_create_GTF script?

**Comment by fairliereese** [comment]
You should try! 

I am curious to find out more about the offending gene. A way to check this would be opening your TALON database in the sqlite browser, navigating to the genes table, seeing if any entries have strands that are not '+' or '-', and then cross-referencing the genes via gene_ID in the gene_annotations table.

If you want, you can zip your db up and send it to me so I can take a look, or I can provide you with ideas on what to print out to figure out what's going on with the TALON get_read_annotations step.

**Comment by abs-yy** [comment]
I finally got it, the GTF file I had used was corrupted, the transcript rows lacked the gene_id field. Thats what made the loss of linkage between tables. Fixed it and the pipeline went on beautifully.
Sorry for the bother!
