### ISSUE TITLE
Export fasta from TALON database?

### ISSUE THREAD

**Issue by joelnitta** [mortazavilab/TALON#67]
Hi, thanks for the excellent software!

This is a feature request, or if there is a way to do this already, I'd like to know how. I want to export a "transcriptome" of all filtered isoforms for downstream analysis. This is basically the same thing as `talon_create_GTF`, but instead of a GTF file it would produce a fasta file. I tried using `gffread` to extract the transcript sequences from the GTF + genome, but this results in the sequences in the genome where the isoforms mapped to, not the isoforms themselves.

Thanks!

**Comment by fairliereese** [comment]
This is an interesting idea. I am a bit confused though, wouldn't the sequences in the genome where the isoforms mapped to be the transcript sequences themselves? Unless you're concerned with pulling out genetic variation as compared to the reference genome.
