### ISSUE TITLE
ValueError: Annotation name 'transcriptome' not found in this database. Try one of the following:

### ISSUE THREAD

**Issue by simonemoro** [mortazavilab/TALON#73]
Hello TALON group,
After running your program I get this message:

**ValueError: Annotation name 'transcriptome' not found in this database. Try one of the following:**

'transcriptome' is the name that I use when I create the database with talon_initialize_database. And I use the same name in talon_abundance and talon_create_GTF. 
Do you know what's the issue here?

Thanks for your help.

**Comment by fairliereese** [comment]
Can you please provide the calls that you made along with the call that specifically throws the error? Which version of TALON are you running?

**Comment by ConnorBarnhill** [comment]
Also having this issue
