### ISSUE TITLE
Any chance of getting bam support?

### ISSUE THREAD

**Issue by oneillkza** [mortazavilab/TALON#76]
Would there be any chance of getting Talon to accept bams as input? We have bams >100GB. We basically never store these as sams, since they'd be 0.5TB each. But to run Talon, I have to uncompress back to sam.

This probably also slows down the execution of Talon, as I'd imagine it'd be much faster to read in from bam.

Would it be possible to get bam file support? Or alternately, reading from stdin so that samtools/sambamba view output could be piped to it directly?

**Comment by oneillkza** [comment]
Note: this seems extra silly, since it looks like the first thing TALON does is turn the sam back into a bam.

But when I tried to pass it a bam in the config file, it threw and error saying it needed sam input.

**Comment by fairliereese** [comment]
Thank you for the suggestion - I agree that this would be a nice quality of life improvement for TALON. We are planning a TALON upgrade in the coming months and will try to roll this into it!

**Comment by oneillkza** [comment]
Thanks -- it would be a huge quality of life improvement. I'm running TALON now on a whole PromethION flowcell's worth of RNA-seq (>100M reads), and it needs about 700GB of extra storage to turn the BAM into SAM and then have TALON turn it back into BAM again. It's also taking about 18 hours to do all that, since it seems to be single-threaded.

**Comment by fairliereese** [comment]
If you're interested in trying it out, I added BAM support to the [development branch](https://github.com/mortazavilab/TALON/tree/development). I think it would also make sense to add the multithreading option to the SAM to BAM conversion in line with as many threads as are already given to TALON, so I can do that as well.

**Comment by callumparr** [comment]
> If you're interested in trying it out, I added BAM support to the [development branch](https://github.com/mortazavilab/TALON/tree/development). I think it would also make sense to add the multithreading option to the SAM to BAM conversion in line with as many threads as are already given to TALON, so I can do that as well.

Is this now brought into a main branch or a new release? I am currently using TALON 5.0. 

Does this branch also have support for multi-thread handling of SAM/BAM manipulations?

**Comment by fairliereese** [comment]
Hi! Yes, this change has been made as part of the main TALON branch. You will have to `git clone` it and `pip install .` from the resulting TALON directory to make it usable. And yes, all of the sam / bam manipulations are now multithreaded.

**Comment by callumparr** [comment]
> Hi! Yes, this change has been made as part of the main TALON branch. You will have to `git clone` it and `pip install .` from the resulting TALON directory to make it usable. And yes, all of the sam / bam manipulations are now multithreaded.

Cool! THank you will do this.

**Comment by callumparr** [comment]
It is now reading BAM inputs but it is still sorting them even though the inputs are sorted. I think talon_label outputs a sorted BAM/SAM file. So why the need to sort the alignment file when starting in the first step before mering in TALON?

**Comment by fairliereese** [comment]
> Does this branch also have support for multi-thread handling of SAM/BAM manipulations?

Actually I was wrong when I replied to this originally. The threads options were not being passed through correctly but should be now if you install the latest commits. Sorry about that!
