### ISSUE TITLE
tmp file 

### ISSUE THREAD

**Issue by YZYwoazzzzz** [mortazavilab/TALON#78]
hi guys,
In talon step, a talon_tmp dir was created. But many pybedtools.*.tmp files were generated in my root /tmp dir. How to fix it?
Thx.
Y

**Comment by fairliereese** [comment]
Hi, 

I'm not sure I understand your question. Is this the same problem as https://github.com/mortazavilab/TALON/issues/74?

**Comment by YZYwoazzzzz** [comment]
Hi fairliereese,
Thanks for response.
I am not familiar with python scripts, but I think there may be an issue with pybedtools. It generates  pybedtools.*.tmp files in /tmp/* file by default. I see that in  https://daler.github.io/pybedtools/topical-design-principles.html. And the /tmp/* files were not deleted when transcriptclean finished. 
I add a line in transcriptclean.py: 
pybedtools.set_tempdir('/mypath/tmp') 
And manually remove this tmp dir after runing.

Y

**Comment by fairliereese** [comment]
Ah I see. That definitely does seem weird, but perhaps maybe something that could be solved in TranscriptClean as opposed to TALON.
