### ISSUE TITLE
N replicates for whitelist

### ISSUE THREAD

**Issue by callumparr** [mortazavilab/TALON#79]
I want to make a whitelist to remove novel entries that may not be that well supproted. My experimental design is several conditions of age, gender, and housing for mouse brain samples (~34 samples in total and roughly 3-5 per condition each). However, I was thinking in terms of replicates for whitelist what would be termed a biological replicate. I could supply all 34 samples but that seems excessively stringent. But if I use fewer should I use mice samples from across the conditions or and then how many replicates per condition. Or should I make a separate whitelist for each condition (using each replicate mouse for that condition) and compare what drops out. 

I guess my question is how should we restrict for finding something novel. It would seem obvious when maybe comparing species or cell types but in my case I am little confused how to proceed.

**Comment by fairliereese** [comment]
This is really subjective based on your experimental design. What I might do on a dataset such as this is indeed make a pass list for each condition and then take the union of those pass lists. 

With regards to how many replicates you require each transcript to be reproducible in, again, this is pretty subjective. If you have spike ins you can try a parameter space exploration varying the fraction A, n datasets, and n reads options to `talon_filter_transcripts` to maximize the sensitivity and specificity of your filtering settings. If not, my default is usually to just go for at least 5 reads in at least 2 replicates, with the default internal priming filter.

**Comment by callumparr** [comment]
TY very much for your reply. It's very useful. May I ask how to interpret the `whitelist.csv` file. Do the numbers refer to the order in which an isoform appears in the `TALON.db`? So after running for each condition I can combine the different whitelists using `uniq` to make sure not to duplicate when a whitelist isoform appears in more than one condition?

**Comment by callumparr** [comment]
Ah related to the internal priming. Should we be more lenient if using direct RNA sequencing as biochemically I think it is harder for the RT to be primer internally as the RT priming is linked with the 3'-end OH ligation event of the split adapter?

**Comment by fairliereese** [comment]
> TY very much for your reply. It's very useful. May I ask how to interpret the `whitelist.csv` file. Do the numbers refer to the order in which an isoform appears in the `TALON.db`? So after running for each condition I can combine the different whitelists using `uniq` to make sure not to duplicate when a whitelist isoform appears in more than one condition?

The pass list file includes the gene ID and the transcript ID that TALON uses internally to track genes and transcripts. You can get the union by `cat`ing all the output pass lists together and then calling `uniq` on that, yes. 

> Ah related to the internal priming. Should we be more lenient if using direct RNA sequencing as biochemically I think it is harder for the RT to be primer internally as the RT priming is linked with the 3'-end OH ligation event of the split adapter?

I think this would make sense, though you know your assay best!

**Comment by callumparr** [comment]
TY for your help. Much appreciated.
