### ISSUE TITLE
Many GENCODE transcripts are missing in talon_create_GTF output

### ISSUE THREAD

**Issue by hd00ljy** [mortazavilab/TALON#82]
I have two sets of samples, A and B

After I discover novel isoforms in sample set A,
I want to quantify them in sample set B,  together with known GENCODE transcripts.

In order to do that,
I need a GTF file consisting of entire known GENCODE transcripts + novel transcripts(named TALONT~) from sample set A

But when I generated gtf after running talon on sample set A,
I found out that many knwon GENCODE transcripts were filtered out even if I did not set --observed when running talon_create_GTF.

**Is there a way to preserve GENCODE transcripts that have not been observed?**
Or am I doing something wrong?

--------------
here are the codes I ran with my sample set A

```
time talon_initialize_database \
 --f gencode_v36.gtf \
 --a setA_isoforms \
 --g hg38 \
 --o talondb


talon \
      -t 8 \
      --f config.csv \
      --db talondb.db \
      --build hg38 \
      --o setA_out \
      -c $th_cov \
      -i $th_id

mailing "read annot generated" || echo 1



##abundance : prefilter
talon_abundance \
       --db talondb.db \
       -a setA_isoforms  \
       --build hg38 \
       --o setA_out

##abundance : postfilter - FracA, SR reads

talon_filter_transcripts  \
       --db talondb.db \
       --datasets $(cut -f 1 -d "," ${cfg} | awk 'NR!=1{printf ","}{printf $1}') \
       -a setA_isoforms \
       --maxFracA $th_fA \
       --minCount $th_SR \
       --minDatasets 1 \
       --o setA_out_filtered_transcripts.csv

talon_abundance \
       --db talondb.db \
       --whitelist setA_out_filtered_transcripts.csv \
       -a setA_isoforms  \
       --build hg38 \
       --o setA_out_filtered

talon_create_GTF  \
       --db talondb.db \
       --whitelist setA_out_filtered_transcripts.csv \
       -a setA_isoforms  \
       --build hg38 \
       --o setA_out_filtered.gtf

```

out of 232,117 GENCODE transcripts, only 46,688 GENCODE transcripts were in the final output file : setA_out_filtered.gtf_talon.gtf

**Comment by fairliereese** [comment]
Hi there! If you're using a pass list from your filtering to make the GTF (which you are!), the _only_ transcripts that will make it into the resultant GTF are those that passed filtering. From your `talon_filter_transcripts` call, since you passed a specific list of datasets, TALON's behavior is to only output the transcripts that are present in one of those datasets, which is typically a subset of GENCODE transcripts, not all of them.

**Comment by hd00ljy** [comment]
Thank you for the answer!

Then is there a way to get a gtf file of total(unfiltered) GENCODE transcripts + filtered novel transcripts that are properly sorted?

**Comment by fairliereese** [comment]
Unfortunately there isn't a way to do it as the tool currently exists. However, here's some workaround Python code to generate a filtered pass list that contains all the annotated models as well as the novel models that passed filtering. You can use the output csv from this code to generate your GTF!

```python
import pandas as pd

abundance_file = "your unfiltered TALON abundance file.tsv"
pass_list = "your filtered pass list.csv"
output_file = "your output filename.csv"

pass_list = pd.read_csv(pass_list, header=None, names=['gene_ID', 'transcript_ID'])
df = pd.read_csv(abundance_file, sep='\t')
df = df.loc[df.transcript_novelty == 'Known']
df = pd.concat([df, pass_list])
df.drop_duplicates(inplace=True)
df.to_csv(output_file, header=None, index=False)
```

Let me know if this works for you!

**Comment by hd00ljy** [comment]
Thank you for writing the python script code!
It seems to work for me!

**Comment by callumparr** [comment]
> I have two sets of samples, A and B
> 
> After I discover novel isoforms in sample set A, I want to quantify them in sample set B, together with known GENCODE transcripts.
> 
> In order to do that, I need a GTF file consisting of entire known GENCODE transcripts + novel transcripts(named TALONT~) from sample set A
> 
> But when I generated gtf after running talon on sample set A, I found out that many knwon GENCODE transcripts were filtered out even if I did not set --observed when running talon_create_GTF.
> 
> **Is there a way to preserve GENCODE transcripts that have not been observed?** Or am I doing something wrong?
> 
> here are the codes I ran with my sample set A
> 
> ```
> time talon_initialize_database \
>  --f gencode_v36.gtf \
>  --a setA_isoforms \
>  --g hg38 \
>  --o talondb
> 
> 
> talon \
>       -t 8 \
>       --f config.csv \
>       --db talondb.db \
>       --build hg38 \
>       --o setA_out \
>       -c $th_cov \
>       -i $th_id
> 
> mailing "read annot generated" || echo 1
> 
> 
> 
> ##abundance : prefilter
> talon_abundance \
>        --db talondb.db \
>        -a setA_isoforms  \
>        --build hg38 \
>        --o setA_out
> 
> ##abundance : postfilter - FracA, SR reads
> 
> talon_filter_transcripts  \
>        --db talondb.db \
>        --datasets $(cut -f 1 -d "," ${cfg} | awk 'NR!=1{printf ","}{printf $1}') \
>        -a setA_isoforms \
>        --maxFracA $th_fA \
>        --minCount $th_SR \
>        --minDatasets 1 \
>        --o setA_out_filtered_transcripts.csv
> 
> talon_abundance \
>        --db talondb.db \
>        --whitelist setA_out_filtered_transcripts.csv \
>        -a setA_isoforms  \
>        --build hg38 \
>        --o setA_out_filtered
> 
> talon_create_GTF  \
>        --db talondb.db \
>        --whitelist setA_out_filtered_transcripts.csv \
>        -a setA_isoforms  \
>        --build hg38 \
>        --o setA_out_filtered.gtf
> ```
> 
> out of 232,117 GENCODE transcripts, only 46,688 GENCODE transcripts were in the final output file : setA_out_filtered.gtf_talon.gtf

This python script will create a new list of gene and transcripts IDs as they are known within TALON database for your filtered whitelist and then the observed BUT not filtered transcripts from the unfiltered abundance file. That is there must be a least one documented reads assigned to that transcript with the TALON database. 

If you want to create a GTF that has every existing annotated transcript including ones observed in you datasest whether you filtere them or not, and the novel TALON transcripts you'd have to do something else as currently annotated ENST transcripts will obviously not have a TALON generated index ID in which to output to GTF sorted with your TALONTs.

**Comment by fairliereese** [comment]
You're absolutely right; not sure why I provided the code that I did as the answer. Here's an updated version of the Python code to _actually_ accomplish this:

```python
import sqlite3
import pandas as pd

db = 'your talon db'
pass_list = 'your filtered pass list'
new_pass_list = 'output file name for pass list w/ all gencode'

df = pd.read_csv(pass_list, header=None, names=['gene_ID', 'transcript_ID'])

with sqlite3.connect(db) as conn:
    query = """SELECT DISTINCT t.gene_ID, t.transcript_ID
                    FROM transcripts as t
                    LEFT JOIN transcript_annotations as ta
                        ON ta.ID = t.transcript_ID
                    WHERE (ta.attribute = 'transcript_status'
                        AND ta.value = 'KNOWN')
            """
    annot = pd.read_sql_query(query, conn)

df = pd.concat([annot, df])

df.to_csv(new_pass_list, header=None, index=False)


```

**Comment by callumparr** [comment]
Sorry to bring up an old closed feed but I was trying and failing to do this myself. As planning to use GTF on new samples wanted to have all existing gencode plus novel transcripts in one file to make things easier.

**Comment by callumparr** [comment]
> ```python
> import sqlite3
> import pandas as pd
> 
> db = 'your talon db'
> pass_list = 'your filtered pass list'
> new_pass_list = 'output file name for pass list w/ all gencode'
> 
> df = pd.read_csv(pass_list, header=None, names=['gene_ID', 'transcript_ID'])
> 
> with sqlite3.connect(db) as conn:
>     query = """SELECT DISTINCT t.gene_ID, t.transcript_ID
>                     FROM transcripts as t
>                     LEFT JOIN transcript_annotations as ta
>                         ON ta.ID = t.transcript_ID
>                     WHERE (ta.attribute = 'transcript_status'
>                         AND ta.value = 'KNOWN')
>             """
>     annot = pd.read_sql_query(query, conn)
> 
> df = pd.concat([annot, df])
> 
> df.to_csv(new_pass_list, header=None, index=False)
> ```

I added additiona line to drop the duplicates as the pass_list I have includes some filtered gencode annotations

`>>> df.drop_duplicates(inplace=True)`

Thank you for the script is very useful.
