### ISSUE TITLE
Does TALON provide junction tolerance parameter?

### ISSUE THREAD

**Issue by hd00ljy** [mortazavilab/TALON#84]
Does TALON provide a junction tolerance parameter?

Since the long read RNA-seq data usually have high error rates, clustering reads with splice junctions at similar but not identical positions may actually come from the same isoform.

As far as I checked, TALON provides 5' and 3' parameters in but it seems to be tolerance for TSS and TES.

Please let me know if I missed something.

**Comment by fairliereese** [comment]
Hi there, great question!

TALON trusts the splice junctions found in the mapped input SAM files and does not attempt to correct them. Internally, our group uses a preprocessing tool called [TranscriptClean](https://github.com/mortazavilab/TranscriptClean) that was designed to clean up common long-read sequencing errors, such as problems with the splice junctions. Running a tool such as this one before running TALON would help consolidate isoforms on the basis of their splice junctions. Another similar option I'm familiar with is [FLAIR's "correct" module](https://github.com/BrooksLabUCSC/flair#correct). 

Let me know if this doesn't answer your question!

**Comment by hd00ljy** [comment]
Thank you for your comments! I'll try those tools.
