### ISSUE TITLE
Issues with some plotting scripts in 2020 paper

### ISSUE THREAD

**Issue by callumparr** [mortazavilab/TALON#86]
Sorry I raised some issues in the different repository but wasn't sure if they'd be better linked to here as well.

Is there any plans to release docker of the analysis and plotting scripts because I had some issues with versions of python, R and various module, packages. 

If you can help with these issues in anyway it be much appreciated. I've also tried running the two plotting scripts on example data in TALON-5 and getting errors. 

https://github.com/mortazavilab/TALON-paper-2020/issues/3#issue-1020158781 

https://github.com/mortazavilab/TALON-paper-2020/issues/2#issue-1020127301

**Comment by fairliereese** [comment]
Hi, 

There are no plans to do so. I can try to help with your individual issues though on the repo. As an aside, the existence of the repo was more of a reference for ourselves which hopefully explains why it doesn't seem to be so user friendly, so I apologize for that. I'll look into your issues on the other repo though.

**Comment by callumparr** [comment]
Thank you very much!
