### ISSUE TITLE
specific genome ref

### ISSUE THREAD

**Issue by xiaonalu** [mortazavilab/TALON#89]
Hi, Is there a specific genome ref works for TALON? I used the GRCm39 and GRCm38 of mouse, both received similar error as below.
KeyError: 'chr16 not in GCF_000001635.27_GRCm39_genomic.fa.'
KeyError: 'chr14 not in GCF_000001635.27_GRCm39_genomic.fa.'

Thanks

**Comment by fairliereese** [comment]
This sounds like a mismatch between the chromosome names that are in your input SAM files and your reference GTF. Please check to make sure they are formatted the same way!
