### ISSUE TITLE
ValueError: Annotation name 'aranno' not found in this database. Try one of the following:

### ISSUE THREAD

**Issue by JD12138** [mortazavilab/TALON#91]
Hello TALON group,
After running your program I get this message:
**ValueError: Annotation name 'aranno' not found in this database. Try one of the following:**

'aranno' is the name that I use when I create the database with talon_initialize_database. And I use the same name in talon_abundance.
I think there are no annotation name in my database because the "Try one of the following" is null.
These are my command for initialize database and talon_abundance:
**talon_initialize_database --f $gtf \
  --a ar_anno \
  --g ar_genome \
  --o ./ar_db**

t**alon_abundance \
  --db ar_db.db \
  --build ar_genome \
  -a ar_anno \
  --o ./talon_abundance**

Do you know what's the issue here?

Thanks for your help.

**Comment by fairliereese** [comment]
Hi, 

Are you sure TALON finished running to completion? My first thought is that it might be empty. Can you check your output files to ensure that it finished running?

**Comment by rkyger-git** [comment]
Hello fairliereese, 

I ran into this same issue above, when trying to run either **talon_filter_transcripts** or **talon_abundance**.
Neither my .db file, nor the output files from the previous step ("Running TALON"), are empty. 
Do you know what might be causing the problem?
