### ISSUE TITLE
talon says my files dont exist

### ISSUE THREAD

**Issue by abrantesas** [mortazavilab/TALON#92]
Hi, thanks for making this software available! Any help is appreciated!

 I call Talon like this: 

talon  --f ./03analysis/talon/TALONconfig.csv \
       --db ./03analysis/talon/lr2020talon.db \
       --build hg38 -t 8 \
       --o lr2020

and I immediately get this error: 

Traceback (most recent call last):
  File "/nas/longleaf/home/abrantes/modules/anaconda2/envs/longread2020/bin/talon", line 8, in <module>
    sys.exit(main())
  File "/nas/longleaf/home/abrantes/modules/anaconda2/envs/longread2020/lib/python3.7/site-packages/talon/talon.py", line 2400, in main
    sam_files, dset_metadata = check_inputs(options)
  File "/nas/longleaf/home/abrantes/modules/anaconda2/envs/longread2020/lib/python3.7/site-packages/talon/talon.py", line 1414, in check_inputs
    raise ValueError("SAM file '%s' does not exist!" % curr_sam)
ValueError: SAM file '"/nas/depts/007/sullilab/shared/longread_2020/03analysis/talon/labeled/pt_043_001/pt_043_001_labeled.sam"' does not exist!

It isn't just a typo. I can copy directly from the error output and paste into the console to view the file it claims is missing.

TranscriptClean, talon label_reads, and talon initialize_database appear to have worked fine so far in the pipeline.

Anthony

**Comment by fairliereese** [comment]
Hi, is it possible that your sam files are symlinked?

**Comment by abrantesas** [comment]
I don't think so. The files were created by talon_label_reads according to the tutorial here.

**Comment by fairliereese** [comment]
Did you try to `ls` the file that TALON allegedly can't find in your bash terminal? It's certainly worth double checking.

**Comment by abrantesas** [comment]
I have never worked with symbolic links so I am not sure what I am looking for. If I run ls -hs in the folder I see the labeled.sam file and the read_labels.tsv and that they are 9.4G and 113M in size.

**Comment by fairliereese** [comment]
Can you use the absolute path that's in your config file instead of just relying on relative paths? It would help if you send me your config file.

**Comment by abrantesas** [comment]
[TALONconfig.csv](https://github.com/mortazavilab/TALON/files/7914150/TALONconfig.csv)

Thanks for the help. What do you mean by that? If I type "ls /nas/depts/007/sullilab/shared/longread_2020/03analysis/talon/labeled/pt_043_001/pt_043_001_labeled.sam" the console just echoes /nas/depts/007/sullilab/shared/longread_2020/03analysis/talon/labeled/pt_043_001/pt_043_001_labeled.sam

**Comment by fairliereese** [comment]
What you mention in that post is exactly what I meant. I just wanted to make sure you had absolute paths listed in your config file. 

Now that I'm confident that your file indeed exists, I'm wondering if you're trying to run TALON on a cluster as a job where perhaps the compute nodes do not have access to where you've stored the file. This has happened to me in the past and is really the only explanation I can think of at this time.
