### ISSUE TITLE
Mostly novel transcripts for genes (mm10/hg38)

### ISSUE THREAD

**Issue by calhoujd** [mortazavilab/TALON#96]
Dear TALON group,

Our lab has been using TALON to analyze a few long read transcriptome datasets (both mouse and human). We've been noticing that for some of the genes we are interested in, TALON assigns the correct gene name, but the overwhelming majority of reads are labeled as novel transcripts. While we expect to identify novel transcripts as we know the Gencode annotation for these genes is far from perfect, it does seem a bit odd that hardly any of the transcripts are a match for a known, annotated transcript. At first, we thought maybe skipping the TranscriptClean step may have been the culprit, but we haven't seen much difference in TALON output for samples run with or without TranscriptClean. 

By comparison, salmon is assigning many of the transcripts from the same samples to known, annotated transcripts, and we are having trouble figuring out why there is such a discrepancy. Any advice on how to sort this out would be appreciated. We are mostly running on publicly available data as a test bed, but are planning more of our own long read sequencing projects in the near future. Thanks!

Take care,

Jeff

PS - Happy to share scripts, snippets of files, etc.

**Comment by callumparr** [comment]
When you salmon is assigning reads to known transcripts is that running salmon with the expanded transcriptome/annotation output from TALON or the original reference transcriptome from gencode/ensembl? 

Salmon make its best attempt to align to reference however of course there could well be a superior alignment but not yet seen in the reference (hence using TALON). 

I also see many, many novel transcripts but this is greatly reduced once going through the various filtering steps, such as minimum number of reads per model, number of replicates, across biological samples etc. I went down from something like over 2 million entries to around 105,000 annotations of which ~30,000 were novel.

**Comment by fairliereese** [comment]
While I agree with @callumparr that filtering might help alleviate the high number of novel transcripts, I do think it is odd that the majority of your _reads_ are novel. If you wouldn't mind, it would indeed be helpful if you could point me to the dataset you're using, as well as your scripts.

If you also have it, a breakdown of the read count per novelty category would be great. You can get this from the TALON read_annot file using the following code:
```bash
cat <read_annot> | cut -f17 | sort | uniq -c
```

One specific case that I'm suspicious of is that TALON expects reads to be oriented all in the same direction (ie 5' -> 3'). If you see a huge number of antisense transcripts as output from the above snippet, this might be your problem!

**Comment by calhoujd** [comment]
> When you salmon is assigning reads to known transcripts is that running salmon with the expanded transcriptome/annotation output from TALON or the original reference transcriptome from gencode/ensembl?
> 
> Salmon make its best attempt to align to reference however of course there could well be a superior alignment but not yet seen in the reference (hence using TALON).
> 
> I also see many, many novel transcripts but this is greatly reduced once going through the various filtering steps, such as minimum number of reads per model, number of replicates, across biological samples etc. I went down from something like over 2 million entries to around 105,000 annotations of which ~30,000 were novel.

Hi @callumparr,

I have been using the standard genome reference for salmon rather than the expanded TALON reference. My problem is that even without filtering, all but ~6 reads are considered novel transcripts. Filtering might improve slightly the ratio of novel/known, but I have so few known to begin with that something seems a bit off.

Take care,

Jeff

**Comment by calhoujd** [comment]
Hi @fairliereese,

Thank you for offering to investigate this. One of the datasets I am using is the long-read transcriptome data from the scisorseqr publication (github link: https://github.com/noush-joglekar/scisorseqr). I am happy to share files. Do you have a preference of GoogleDrive or OneDrive? I used to use Box but our institution recently switched to OneDrive. Also, would you please provide an email address so I can give you permission to view the folder? If you don't want to post here, feel free to send me an email, contact info below. Thank you in advance for helping us sort this out!

Take care,

Jeff

Jeff Calhoun
jeffrey [dot] calhoun [at] northwestern [dot] edu

PS - I have a grant due today, but I will run the code you suggested as soon as possible and share
