### ISSUE TITLE
Optimal setting to identify alternate 3' and 5' ends

### ISSUE THREAD

**Issue by jchariker** [mortazavilab/TALON#97]
Hi,
I'm interested in identifying alternate 3' and 5' ends of transcripts. What would be the best settings for this? I see the options --5p and --3p in talon_initialize_database, but I'm not quite sure what effect they have. 
Thanks!

**Comment by fairliereese** [comment]
The `--3p` and `--5p` parameters tune the maximum distance that an end observed from a read can be from the annotated end for the read to still be annotated as a known transcript. If a read matches the intron chain of an annotated transcript but the ends of the read are not within the distance parameters, it will be annotated as a novel transcript. In contrast, a read with the same intron chain with ends that are within the parameters, the end assigned to the read will simply be the read from the annotation.

This is rather unfortunate as it does cloud the underlying ends of each known read and is a problem we're actively working on in the lab. The current tool that we're using to cluster and call 5'/3' ends from transcripts is [lapa](https://github.com/mortazavilab/lapa), which will work on either the `read_annot.tsv` file output from TALON, or the bam files that you input to TALON.

**Comment by YichaoOU** [comment]
Hi @[fairliereese](https://github.com/fairliereese), can you provide more details on how to use `lapa`? 

It seems that we should use `lapa_correct_talon` instead of `lapa`? Once we have the gtf from lapa, we need to run talon to quantify abundance again, right?

Thanks,
Yichao

**Comment by fairliereese** [comment]
These are questions best suited for the lapa repo. I would ask again there.
